### ISSUE TITLE
Can not read exported resources if the file path includes special characters such as " " or "ö".

### ISSUE THREAD

**Issue by GokayNuray** [GokayNuray/Across-the-Sands-of-Time#1]
I think it has to do with Java's File class, it somehow does not work with special characters.

**Comment by developer-rohith** [comment]
I'm interested in working on this issue and would like to contribute a solution. Is there anything specific I should know before getting started? Looking forward to diving into this!

**Comment by GokayNuray** [comment]
Hello @developer-rohith, thank you for wanting to help! The library i used to import models(Assimp) requires a path to the resource files, so I decided to import model files in a folder next to the exe file. In [https://github.com/GokayNuray/Across-the-Sands-of-Time/blob/master/src/main/java/com/halenteck/render/ModelLoader.java](url) file, exportParentFolderToDiskAndReturnPath method is doing this. But this method throws a "NoSuchFileException" at line 218 if the path contains special methods. I think there is a problem with one of the classes used in this method when it comes to handling special characters, but I do not know which or how to fix it. Any help is appreciated :)

The exe file in the releases runs fine initially, but when you try to join a fps game match, it tries to load the models and stops working if the path includes a special character(you can see the exception on the console which starts with application). You can use it to see the exception yourself.

**Comment by developer-rohith** [comment]
Hello @GokayNuray , I went through the code and did some debugging. what  I didn't understand was substring method starting from index 5 and ending where there is '!' symbol in the line 268 and 215. What I found was the dirURL doesnot contain '!'  symbol and no need to start from index 5 , it can be started from index 0. And another observation is  exportFileToDiskAndReturnPath() executes first before exportParentFolderToDiskAndReturnPath() method. So I have modified both the lines which I mentioned above. However, I got rid of the mentioned errors, but got the new ones. Let me know if you want to review my code

**Comment by GokayNuray** [comment]
@developer-rohith , I think you ran the code directly on your IDE or something like that, which does not reproduce the problem I was talking about. After compressing the project in an executable .jar file(using gradle shadowjar), paths of the files become like this: "jar:/C:/foo/bar.jar!/baz.class". The substring methods are used the remove the jar:/ from the start and the resource name at the end in order to get the path to the jar file, which is then used to create resources next to the executable file.  As for the export file method i didn't think it would create a problem since it also includes code to create folders, but if you think it has some issue it may need to be revised. Hope this message was helpful and thank you for your time!
